pipeline {
    agent any
//     environment{
//         PATH = "/mnt/c/Program Files/apache-maven-3.8.6/bin:$PATH"
//     }
    tools {
       maven 'MAVEN 3.8.6'
    }
    stages {
        stage('Git checkout'){
            steps{
            git branch: 'feature/PatrykJedrzejewski/AUT-135-create-jenkinsfile', credentialsId: '6005038a-2554-49c5-ac38-b1257b3ebf28', url: 'https://github.com/CapGemini-Java-Testing/java-testing'
            }
        }
        stage('Install') {
            steps {
            sh "mvn install -DskipTests"
            }
        }
        stage('Test') {
            steps {
            sh "mvn '-Dtest=Patryk_Jedrzejewski.tests.*Tests' test"
            }
        }
    }
    post {
            always {
                archiveArtifacts artifacts: '**/*.jar', fingerprint: true
            }
    }
}